// TODO IDK WHAT THIS FILE DOES

#ifndef STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_IMPLEMENTATION
//#include <stb_image.h>
#endif // !STB_IMAGE_IMPLEMENTATION

#ifndef STB_IMAGE_WRITE_IMPLEMENTATION
#define STB_IMAGE_WRITE_IMPLEMENTATION
//#include <stb_image_write.h>
#endif // !STB_IMAGE_WRITE_IMPLEMENTATION
